service: express-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1


functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true